puts "Creating positions..."
unclassified_field = Department.find_by_name 'Unclassified Field'
unclassified_corporate = Department.find_by_name 'Unclassified Corporate'
advocates = Department.find_by_name 'Advocates'
hr = Department.find_by_name 'Human Resources'
vonage_retail_sales = Department.find_by_name 'Vonage Retail Sales'
vonage_event_sales = Department.find_by_name 'Vonage Event Sales'
training = Department.find_by_name 'Training'
operations = Department.find_by_name 'Operations'
information_technology = Department.find_by_name 'Information Technology'
sprint_retail_sales = Department.find_by_name 'Sprint Retail Sales'

Position.create [
                    { name: 'System Administrator',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: information_technology.id,
                      field: false,
                      hq: true },
                    { name: 'Unclassified Field Employee',
                      leadership: false,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: unclassified_field.id,
                      field: true,
                      hq: false },
                    { name: 'Unclassified Corporate Employee',
                      leadership: false,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: unclassified_corporate.id,
                      field: false,
                      hq: true },
                    { name: 'Advocate Supervisor',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: false,
                      department_id: advocates.id,
                      field: false,
                      hq: true },
                    { name: 'Advocate',
                      leadership: false,
                      all_field_visibility: true,
                      all_corporate_visibility: false,
                      department_id: advocates.id,
                      field: false,
                      hq: true },
                    { name: 'Advocate Director',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: false,
                      department_id: advocates.id,
                      field: false,
                      hq: true },
                    { name: 'HR Administrator',
                      leadership: false,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: hr.id,
                      field: false,
                      hq: true },
                    { name: 'HR Administrator Supervisor',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: hr.id,
                      field: false,
                      hq: true },
                    { name: 'Senior Software Developer',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: information_technology.id,
                      field: false,
                      hq: true },
                    { name: 'Training Director',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: training.id,
                      field: false,
                      hq: true },
                    { name: 'Field Training Director',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: false,
                      department_id: training.id,
                      field: true,
                      hq: false },
                    { name: 'Trainer',
                      leadership: false,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: training.id,
                      field: false,
                      hq: true },
                    { name: 'Field Trainer',
                      leadership: false,
                      all_field_visibility: true,
                      all_corporate_visibility: false,
                      department_id: training.id,
                      field: true,
                      hq: false },
                    { name: 'Vice President of Operations',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: operations.id,
                      field: false,
                      hq: true },
                    { name: 'Operations Coordinator',
                      leadership: false,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: operations.id,
                      field: false,
                      hq: true },
                    { name: 'Vonage Retail Regional Vice President',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: vonage_retail_sales.id,
                      field: true,
                      hq: false },
                    { name: 'Vonage Event Regional Vice President',
                      leadership: true,
                      all_field_visibility: true,
                      all_corporate_visibility: true,
                      department_id: vonage_event_sales.id,
                      field: true,
                      hq: false },
                    { name: 'Vonage Retail Regional Manager',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_retail_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Vonage Event Regional Manager',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_event_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Sprint Retail Regional Manager',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: sprint_retail_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Vonage Retail Area Sales Manager',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_retail_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Vonage Event Area Sales Manager',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_event_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Vonage Event Team Leader',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_event_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Vonage Retail Territory Manager',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_retail_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Sprint Retail Territory Manager',
                      leadership: true,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: sprint_retail_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Vonage Retail Sales Specialist',
                      leadership: false,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_retail_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Vonage Event Sales Specialist',
                      leadership: false,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: vonage_event_sales.id,
                      field: true,
                      hq: false  },
                    { name: 'Sprint Retail Sales Specialist',
                      leadership: false,
                      all_field_visibility: false,
                      all_corporate_visibility: false,
                      department_id: sprint_retail_sales.id,
                      field: true,
                      hq: false  }
                ]