Rails.application.config.assets.precompile += %w( masonry.min.js )
Rails.application.config.assets.precompile += %w( jquery-ui-datepicker.js )
Rails.application.config.assets.precompile += %w( home.js )
Rails.application.config.assets.precompile += %w( people.js )
Rails.application.config.assets.precompile += %w( sessions.js )
Rails.application.config.assets.precompile += %w( google_jsapi.js )
Rails.application.config.assets.precompile += %w( lines.js )
Rails.application.config.assets.precompile += %w( devices.js )
Rails.application.config.assets.precompile += %w( log_entries.js )
Rails.application.config.assets.precompile += %w( device_deployments.js )
Rails.application.config.assets.precompile += %w( widgets.js )

