sdesjarlais@retaildoneright.com: Training Director
mgallenstein@retaildoneright.com: Advocate Director
matt@retaildoneright.com: Information Technology Director
rwatier@retaildoneright.com: Inventory Coordinator
rcushing@retaildoneright.com: Operations Director
emontesdeoca@retaildoneright.com: Finance Administrator
bzopolsky@retaildoneright.com: Controller
cwilcox@retaildoneright.com: Accountant
sriker@retaildoneright.com: Marketing Director
rdarling@retaildoneright.com: Reporting Coordinator
charris@retaildoneright.com: Quality Assurance Director
jimmy@retaildoneright.com: Chief Executive Officer
kevin@retaildoneright.com: Chief Operations Officer
cdipasquale@retaildoneright.com: Chief Financial Officer
dharty@retaildoneright.com: Vice President of Sales
mtotan@retaildoneright.com: Payroll Director
lrozar@retaildoneright.com: Payroll Administrator
jcullen@retaildoneright.com: Human Resources Director
msrinivasa@retaildoneright.com: Information Technology Support Technician
zmathew@retaildoneright.com: Information Technology Support Technician
sgoudard@retaildoneright.com: Information Technology Support Technician
nhissa@retaildoneright.com: Operations Coordinator
mhafer@retaildoneright.com: Executive Assistant
dshort@retaildoneright.com: Executive Assistant
jhade@retaildoneright.com: Sprint Retail Regional Manager
rpitman@retaildoneright.com: Sprint Retail Regional Manager
tkarlin@retaildoneright.com: Comcast Retail Regional Vice President
bgruver@retaildoneright.com: Comcast Retail Regional Vice President
bcarter@retaildoneright.com: Sprint Retail Regional Vice President