aatkinson@retaildoneright.com: Senior Software Developer
smiles@retaildoneright.com: Software Developer
sdesjarlais@retaildoneright.com: Training Director
matt@retaildoneright.com: Information Technology Director
rwatier@retaildoneright.com: Inventory Coordinator
rcushing@retaildoneright.com: Operations Director
emontesdeoca@retaildoneright.com: Finance Administrator
bzopolsky@retaildoneright.com: Controller
cwilcox@retaildoneright.com: Accountant
sriker@retaildoneright.com: Marketing Director
rdarling@retaildoneright.com: Reporting Coordinator
charris@retaildoneright.com: Quality Assurance Director
jimmy@retaildoneright.com: Chief Executive Officer
kevin@retaildoneright.com: Chief Operations Officer
cdipasquale@retaildoneright.com: Chief Financial Officer
dharty@retaildoneright.com: Vice President of Sales
mtotan@retaildoneright.com: Payroll Director
lrozar@retaildoneright.com: Payroll Administrator
jcullen@retaildoneright.com: Human Resources Director
msrinivasa@retaildoneright.com: Information Technology Support Technician
zmathew@retaildoneright.com: Information Technology Support Technician
sgoudard@retaildoneright.com: Information Technology Support Technician
nhissa@retaildoneright.com: Operations Coordinator
mhafer@retaildoneright.com: Executive Assistant
dshort@retaildoneright.com: Executive Assistant
jhade@retaildoneright.com: Sprint Retail Regional Manager
rpitman@retaildoneright.com: SalesMakers Support Member
jparlette@salesmakersinc.com: SalesMakers Support Member
apolancodelahoz@retaildoneright.com: SalesMakers Support Member
anthwilliams@retaildoneright.com: SalesMakers Support Member
tbeverly@retaildoneright.com: SalesMakers Support Member
ridixon@retaildoneright.com: SalesMakers Support Member
mgiordano@rbd-spr.com: SalesMakers Support Member
severetts@retaildoneright.com: SalesMakers Support Member
rmaley@hireretailpros.com: Advocate Supervisor
jthomas@retaildoneright.com: Advocate Supervisor
mbailey@hireretailpros.com: Human Resources Administrator
abode@hireretailpros.com: Human Resources Administrator
kkarcher@hireretailpros.com: Advocate Supervisor
tkarlin@retaildoneright.com: Comcast Retail Regional Vice President
bgruver@retaildoneright.com: Comcast Retail Regional Vice President
bcarter@retaildoneright.com: Sprint Retail Regional Vice President
jumartinez@retaildoneright.com: Human Resources Administrator
crobinson@retaildoneright.com: Advocate Director
jparlette@retaildoneright.com: SalesMakers Support Member
jtherrien@retaildoneright.com: SalesMakers Support Member
jacarter@hireretailpros.com: Human Resources Administrator
sabaker@hireretailpros.com: Human Resources Administrator
lschuetz@hireretailpros.com: Human Resources Administrator
kstrause@hireretailpros.com: Human Resources Administrator
tawoods@hireretailpros.com: Human Resources Administrator
zgooden@hireretailpros.com: Human Resources Administrator
mhester@hireretailpros.com: Human Resources Administrator
cseaman@hireretailpros.com: Human Resources Administrator
dijackson@hireretailpros.com: Human Resources Administrator
elevy@hireretailpros.com: Advocate Director
agomez@retaildoneright.com: SalesMakers Support Member
smanning@retaildoneright.com: SalesMakers Support Member
ahaziz@retaildoneright.com: Sprint RadioShack Sales Director
tralph@retaildoneright.com: Quality Assurance Director
shall@retaildoneright.com: SalesMakers Support Member
kpelletier@retaildoneright.com: Advocate Director
jkieffer@retaildoneright.com: Advocate
srice@retaildoneright.com: Advocate
zmirza@retaildoneright.com: Advocate
hly@retaildoneright.com: Advocate
khines@retaildoneright.com: Advocate
rrodriguez@retaildoneright.com: Advocate
