# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
#Code Climage Test coverage
require "codeclimate-test-reporter"
CodeClimate::TestReporter.start
require 'pundit/rspec'
require 'support/pundit_matcher'
require 'factory_girl_rails'
require 'vcr'
require 'sidekiq/testing'
require 'sunspot/rails/spec_helper'
require 'rack_session_access/capybara'

RSpec.configure do |config|
  # Uncomment the next line to troubleshoot spec times!
  # config.profile_examples = 10

  config.include FactoryGirl::Syntax::Methods

  config.before :suite do
    DatabaseRewinder.clean_all
    #FactoryGirl.lint
  end

  config.before(:each) do |example|
    CASClient::Frameworks::Rails::Filter.fake("retailingw@retaildoneright.com")
    unless example.metadata[:skip_solr_mocking]
      ::Sunspot.session = ::Sunspot::Rails::StubSessionProxy.new(::Sunspot.session)
    end
  end

  config.after(:each) do |example|
    unless example.metadata[:skip_solr_mocking]
      ::Sunspot.session = ::Sunspot.session.original_session
    end
    DatabaseRewinder.clean
  end
end

VCR.configure do |c|
  c.cassette_library_dir = 'spec/cassettes'
  c.hook_into :webmock
  c.configure_rspec_metadata!
  c.ignore_hosts '127.0.0.1', 'localhost', 'codeclimate.com'
  #c.debug_logger = $stderr #Uncomment this for VCR debugging
  c.default_cassette_options = { :record => :new_episodes }
end